build:
  nodes:
    analysis:
      project_root: .
      project_setup:
        override:
          - "true"
      tests:
        override:
          - php-scrutinizer-run
          - command: phpcs-run
            use_website_config: true
    tests: true
    coverage:
      tests:
        override:
          - command: ./vendor/bin/pest --coverage-clover=coverage.xml
            coverage:
              file: coverage.xml      # Ruta del archivo generado por PHPUnit
              format: clover         # Formato soportado (clover, cobertura, lcov, etc.)
filter:
  excluded_paths:
    - "tests/*"
    - "vendor/"
    - "public/"
checks:
  php: true
coding_style:
  php:
    spaces:
      around_operators:
        bitwise: false
        concatenation: true
      other:
        after_type_cast: false
